### ISSUE TITLE
请问应该使用什么版本的transformers？

### ISSUE THREAD

**Issue by ZechenGao** [JunnYu/ChineseBert_pytorch#12]
我在使用chinesebert库时，出现如下的报错，在注释transformers/tokenization_utils_fast.py中split_special_tokens参数的对应行之后能正常使用。我使用的transformers版本是4.44.1，chinesebert版本是0.2.1，怀疑可能是版本不匹配带来的问题。谢谢～
>>> from chinesebert import ChineseBertTokenizerFast
>>> tokenizer = ChineseBertTokenizerFast.from_pretrained('/mnt/hs-1/usr/gaozechen/code/model_cache/junnyu_ChineseBERT-base')
/home/conda/lib/python3.8/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'BertTokenizer'. 
The class this function is called from is 'ChineseBertTokenizerFast'.
>>> inputs = tokenizer('你是一只猫', return_tensors="pt")
split_special_tokens:  False
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/conda/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3055, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/home/conda/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3163, in _call_one
    return self.encode_plus(
  File "/home/conda/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3237, in encode_plus
    return self._encode_plus(
  File "/home/conda/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py", line 602, in _encode_plus
    batched_output = self._batch_encode_plus(
TypeError: _batch_encode_plus() got an unexpected keyword argument 'split_special_tokens'

**Comment by ZechenGao** [comment]
使用4.14.1版本的transformers可以解决这一问题
